 channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - pandas
     - scipy
     - opencv
     - face_recognition
     - streamlit
     - streamlit_webrtc
     - imutils
     - av
     - imutils
